
PROGRAM MULTIMODEFLOQUET

  USE ATOMIC_PROPERTIES
  USE TYPES
  USE SUBINTERFACE
  USE SUBINTERFACE_LAPACK
  USE ARRAYS 
  USE FLOQUETINITINTERFACE


  IMPLICIT NONE
  TYPE(ATOM)                                       ID
  TYPE(MODE),       DIMENSION(:),   ALLOCATABLE :: FIELDS
  INTEGER,          DIMENSION(:),   ALLOCATABLE :: MODES_NUM
  INTEGER                                          TOTAL_FREQUENCIES,D_MULTIFLOQUET
  INTEGER                                          INFO,m,INDEX0,r
  DOUBLE PRECISION, DIMENSION(:),   ALLOCATABLE :: ENERGY,E_FLOQUET
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H__,U_F,U_AUX,U_B2D,U_F1_red,U_F2_red
  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: P_AVG
  DOUBLE PRECISION                              :: T1,T2

 
  ! ===================================================
  !PARAMETERS REQUIRED TO DEFINE THE DRESSED BASIS
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: U_FD           ! TRANSFORMATION FROM THE BARE TO THE DRESSED BASIS
  DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE   :: E_DRESSED      ! DRESSED SPECTRUM
  INTEGER                                       :: DRESSINGFIELDS, DRESSINGFLOQUETDIMENSION! NUMBER OF DRESSING FIELDS
  INTEGER,          DIMENSION(:), ALLOCATABLE   :: DRESSINGFIELDS_INDICES ! IDENTITY OF THE DRESSING FIELDS

  INTEGER                              :: TOTAL_FREQUENCIES_,NM_,FIELD_INDEX
  TYPE(MODE), DIMENSION(:),ALLOCATABLE :: FIELDS_
  INTEGER,    DIMENSION(:),ALLOCATABLE :: MODES_NUM_
  ! ===================================================

  INTEGER N_,M_
 
  OPEN(UNIT=3,file="qubit_bareoscillation_V1.dat", action="write")
  OPEN(UNIT=4,file="qubit_dressedoscillation_V1.dat", action="write")


  INFO = 0
  CALL FLOQUETINIT(ID,'qubit',INFO)
  ALLOCATE(ENERGY(SIZE(J_Z,1)))
  ALLOCATE(H__(SIZE(J_z,1),SIZE(J_z,1)))
  ALLOCATE(P_AVG(SIZE(J_z,1),SIZE(J_z,1)))
  ALLOCATE(U_AUX(SIZE(J_z,1),SIZE(J_z,1)))
  H__ = J_z
  CALL LAPACK_FULLEIGENVALUES(H__,TOTAL_STATES_LSI,Energy,INFO)
  DEALLOCATE(H__)
  DEALLOCATE(ENERGY)
  
  
  ALLOCATE(MODES_NUM(3))

  MODES_NUM(1) = 1 !(STATIC FIELD)
  MODES_NUM(2) = 1 !(DRIVING BY TWO HARMONICS)
  MODES_NUM(3) = 1 !(DRIVING BY A SECOND FREQUENCY)
  
  TOTAL_FREQUENCIES = SUM(MODES_NUM,1)
  ALLOCATE(FIELDS(TOTAL_FREQUENCIES))
  DO m=1,TOTAL_FREQUENCIES
     ALLOCATE(FIELDS(m)%V(ID%D_BARE,ID%D_BARE))
  END DO
  
  FIELDS(1)%X         = 0.0
  FIELDS(1)%Y         = 0.0
  FIELDS(1)%Z         = 1.0
  FIELDS(1)%phi_x     = 0.0
  FIELDS(1)%phi_y     = 0.0
  FIELDS(1)%phi_z     = 0.0
  FIELDS(1)%omega     = 0.0
  FIELDS(1)%N_Floquet = 0

  FIELDS(2)%X         = 0.125/2.0
  FIELDS(2)%Y         = 0.0
  FIELDS(2)%Z         = 0.0
  FIELDS(2)%phi_x     = 0.0
  FIELDS(2)%phi_y     = 0.0
  FIELDS(2)%phi_z     = 0.0
  FIELDS(2)%omega     = 1.0
  FIELDS(2)%N_Floquet = 5
  
  FIELDS(3)%X         = 0.125*FIELDS(2)%X/2.0
  FIELDS(3)%Y         = 0.0
  FIELDS(3)%Z         = 0.125*FIELDS(2)%X/2.0
  FIELDS(3)%phi_x     = 0.0
  FIELDS(3)%phi_y     = 0.0
  FIELDS(3)%phi_z     = 0.0
  FIELDS(3)%omega     = FIELDS(2)%X/2.0
  FIELDS(3)%N_Floquet = 7

  D_MULTIFLOQUET = ID%D_BARE
  DO r=1,TOTAL_FREQUENCIES
     D_MULTIFLOQUET = D_MULTIFLOQUET*(2*FIELDS(r)%N_Floquet+1)
  END DO

  !=================================================================================
  !==== DEFINITION OF THE DRESSING FIELDS AND DRESSED BASIS AND VARIABLES NEEDED TO DEFINE THE MICROMOTION OPERATOR
  !=================================================================================

  DRESSINGFIELDS = 2   ! NUMBER OF DRESSING FIELDS
  ALLOCATE(DRESSINGFIELDS_INDICES(DRESSINGFIELDS)) ! ARRAY THAT TELL US WHICH OF THE FIELD DEFINED ABOVE ARE THE DRESSING ONES
  DRESSINGFIELDS_INDICES(1) = 1 
  DRESSINGFIELDS_INDICES(2) = 2
  DRESSINGFLOQUETDIMENSION = ID%D_BARE ! EXTENDEND DIMENSION OF THE DRESSED BASIS
  DO m=2,DRESSINGFIELDS
     DRESSINGFLOQUETDIMENSION = DRESSINGFLOQUETDIMENSION*(2*FIELDS(DRESSINGFIELDS_INDICES(m))%N_FLOQUET + 1 )
  END DO
  ALLOCATE(U_FD(DRESSINGFLOQUETDIMENSION,DRESSINGFLOQUETDIMENSION))
  ALLOCATE(E_DRESSED(DRESSINGFLOQUETDIMENSION))
  CALL DRESSEDBASIS_SUBSET(ID,DRESSINGFLOQUETDIMENSION,DRESSINGFIELDS,SIZE(MODES_NUM,1),DRESSINGFIELDS_INDICES,MODES_NUM,FIELDS,&
       & U_FD,E_DRESSED,INFO) ! U_FD IS THE TRANSFORMATION OPERATOR BETWEEN THE BARE AND DRESSED BASIS, BOTH EXTENDED.
  !CALL WRITE_MATRIX(ABS(U_FD)**2)
!  write(*,*) E_DRESSED,SIZE(E_DRESSED,1)
  NM_ = DRESSINGFIELDS  ! NUMBER OF DRESSING MODES
  ALLOCATE(MODES_NUM_(NM_))
  DO r=1,NM_
     MODES_NUM_(r)=modes_num(DRESSINGFIELDS_INDICES(r)) ! NUMBER OF HARMONICS OF THE DRESSING MODES
  END DO
  
  TOTAL_FREQUENCIES_ = SUM(MODES_NUM_,1)  ! TOTAL NUMBER OF DRESSING FREQUENCIES
  ALLOCATE(FIELDS_(TOTAL_FREQUENCIES_))
  DO m=1,TOTAL_FREQUENCIES_
     ALLOCATE(FIELDS_(m)%V(ID%D_BARE,ID%D_BARE)) ! PREPARE SPACE TO SET THE DRESSING HAMILTONIAN COMPONENTS
  END DO
  
  FIELD_INDEX = 1
  DO r=1,DRESSINGFIELDS
     DO m=1,MODES_NUM_(r)
        FIELDS_(FIELD_INDEX) = FIELDS(DRESSINGFIELDS_INDICES(r)+m-1) ! IDENTIFY THE DRESSING FIELDS FROM THE COMPLETE LIST OF FIELDS
        FIELD_INDEX = FIELD_INDEX+1
     END DO
  END DO
  
  


  !=================================================================================
  !== MULTIMODE FLOQUET DRESSED BASIS AND TIME-EVOLUTION OPERATOR IN THE BARE BASIS
  !=================================================================================
  CALL SETHAMILTONIANCOMPONENTS(ID,size(modes_num,1),total_frequencies,MODES_NUM,FIELDS,INFO)
  
  !==== MICROMOTION OPERATOR 
  ALLOCATE(U_F1_red(ID%D_BARE,ID%D_BARE))
  ALLOCATE(U_F2_red(ID%D_BARE,ID%D_BARE))

  N_ = 16!64
  M_ = 16!128
  DO r=1,N_

!!$!========= FIND THE MULTIMODE FLOQUET SPECTRUM 
      

     FIELDS(3)%omega     = FIELDS(1)%Z - FIELDS(2)%X + 2.0*(r-1)*FIELDS(2)%X/64
     CALL MULTIMODEFLOQUETMATRIX(ID,size(modes_num,1),total_frequencies,MODES_NUM,FIELDS,INFO)          
     ALLOCATE(E_FLOQUET(SIZE(H_FLOQUET,1)))
     E_FLOQUET = 0.0  
     U_F = H_FLOQUET ! FOURIER DECOMPOSITION OF THE STATES DRESSED BY MODE NUMBER 
     CALL LAPACK_FULLEIGENVALUES(U_F,SIZE(U_F,1),E_FLOQUET,INFO)
     DEALLOCATE(H_FLOQUET)

     
     ! ===== EVALUATE TIME-EVOLUTION OPERATOR 

     T1 = 0.0
     DO m=1,M_+1
        T2 = (m-1)*16.0*100.0/128.0


        
        ! ===== EVALUATE TIME-EVOLUTION OPERATOR  IN THE BARE BASIS
        U_aux = 0.0
        CALL MULTIMODETIMEEVOLUTINOPERATOR(SIZE(U_F,1),SIZE(MODES_NUM,1),MODES_NUM,U_F,E_FLOQUET,ID%D_BARE,FIELDS,T1,T2,U_AUX,INFO) 
        WRITE(3,*) FIELDS(3)%OMEGA,t2,ABS(U_AUX)**2
        !CALL WRITE_MATRIX(ABS(U_AUX)**2)
        !write(*,*) U_AUX

!!$     !=================================================================================
!!$     !== TRANSFORM THE TIME-EVOLUTION OPERATOR TO THE DRESSED BASIS
!!$     !=================================================================================
!!$        
!!$     !== BUILD THE TIME-DEPENDENT TRANSFORMATIONO BETWEEN THE BARE AND THE RF DRESSED BASIS       
        info =0         
        CALL MULTIMODEMICROMOTION(ID,SIZE(U_FD,1),NM_,MODES_NUM_,U_FD,E_DRESSED,ID%D_BARE,FIELDS_,T1,U_F1_red,INFO)
        !write(*,*) U_F1_red
        CALL MULTIMODEMICROMOTION(ID,SIZE(U_FD,1),NM_,MODES_NUM_,U_FD,E_DRESSED,ID%D_BARE,FIELDS_,T2,U_F2_red,INFO) 
        !write(*,*) U_F2_red


        ! ---- CALCULATE THE TIME-EVOLUTION OPERATOR IN THE DRESSED BASIS USING THE PREVIOUSLY CALCULATED IN THE BARE BASIS
        !WRITE(*,*)
        !WRITE(*,*) MATMUL(U_AUX,U_F1_red)
        U_AUX = MATMUL(TRANSPOSE(CONJG(U_F2_red)),MATMUL(U_AUX,U_F1_red)) 
        WRITE(4,*) FIELDS(3)%OMEGA,t2,ABS(U_AUX)**2
        !write(*,*) MATMUL(U_AUX,U_F1_red)
        !CALL WRITE_MATRIX(ABS(U_AUX)**2)

     END DO
!     write(*,*)
     DEALLOCATE(E_FLOQUET)
     WRITE(3,*)
     WRITE(4,*)
  END DO
  
END PROGRAM MULTIMODEFLOQUET

