PROGRAM MULTIMODEFLOQUET

  USE ATOMIC_PROPERTIES
  USE TYPES
  USE SUBINTERFACE
  USE SUBINTERFACE_LAPACK
  USE FLOQUETINIT_ 
  USE ARRAYS  

  IMPLICIT NONE
  TYPE(MODE),       DIMENSION(:),   ALLOCATABLE :: FIELDS
  TYPE(ATOM)                                       ID
  INTEGER,          DIMENSION(:),   ALLOCATABLE :: MODES_NUM
  INTEGER                                          TOTAL_FREQUENCIES
  INTEGER                                          INFO,m,INDEX0
  DOUBLE PRECISION, DIMENSION(:),   ALLOCATABLE :: ENERGY,E_FLOQUET
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H__,U_F,U_AUX,U_B2D,U_F1,U_F2,U_F1_red,U_F2_red
  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: P_AVG
  DOUBLE PRECISION                              :: T1,T2

  INFO = 0
  CALL FLOQUETINIT('87Rb','B',1,ID,INFO)
  ALLOCATE(ENERGY(SIZE(FZ,1)))
  ALLOCATE(H__(SIZE(Fz,1),SIZE(Fz,1)))
  ALLOCATE(P_AVG(SIZE(Fz,1),SIZE(Fz,1)))
  H__ = Fz
  CALL LAPACK_FULLEIGENVALUES(H__,TOTAL_STATES_LSI,Energy,INFO)
  !WRITE(*,*) ENERGY
  DEALLOCATE(H__)
  DEALLOCATE(ENERGY)
  DEALLOCATE(P_AVG)
  CALL DEALLOCATEALL(ID%id_system)

  INFO = 0
  CALL FLOQUETINIT('87Rb','U',1,ID,INFO)
  ALLOCATE(ENERGY(SIZE(J_z,1)))
  ALLOCATE(H__(SIZE(J_z,1),SIZE(J_z,1)))
  ALLOCATE(P_AVG(SIZE(J_z,1),SIZE(J_z,1)))
  H__ = J_z
  CALL LAPACK_FULLEIGENVALUES(H__,TOTAL_STATES_LSI,Energy,INFO)
  !WRITE(*,*) ENERGY
  DEALLOCATE(H__)
  DEALLOCATE(ENERGY)
  DEALLOCATE(P_AVG)
  CALL DEALLOCATEALL(ID%id_system)

  INFO = 0
  CALL FLOQUETINIT('87Rb','L',1,ID,INFO)
  ALLOCATE(ENERGY(SIZE(J_z,1)))
  ALLOCATE(H__(SIZE(J_z,1),SIZE(J_z,1)))
  ALLOCATE(P_AVG(SIZE(J_z,1),SIZE(J_z,1)))
  H__ = J_z
  CALL LAPACK_FULLEIGENVALUES(H__,TOTAL_STATES_LSI,Energy,INFO)
  !WRITE(*,*) ENERGY
  DEALLOCATE(H__)
  DEALLOCATE(ENERGY)
  DEALLOCATE(P_AVG)
  CALL DEALLOCATEALL(ID%id_system)

  INFO = 0
  CALL FLOQUETINIT('qubit','U',2,ID,INFO)
!  write(*,*) size(J_z,1),J_z,id%id_system
  ALLOCATE(ENERGY(SIZE(J_Z,1)))
  ALLOCATE(H__(SIZE(J_z,1),SIZE(J_z,1)))
  ALLOCATE(P_AVG(SIZE(J_z,1),SIZE(J_z,1)))
  H__ = J_z
  CALL LAPACK_FULLEIGENVALUES(H__,TOTAL_STATES_LSI,Energy,INFO)
  !WRITE(*,*) ENERGY
  DEALLOCATE(H__)
  DEALLOCATE(ENERGY)
  DEALLOCATE(P_AVG)
  CALL DEALLOCATEALL(ID%id_system)

  INFO = 0
  CALL FLOQUETINIT('spin','U',1,ID,INFO)
  !write(*,*) size(J_z,1),J_z,id%id_system
  ALLOCATE(ENERGY(SIZE(J_Z,1)))
  ALLOCATE(H__(SIZE(J_z,1),SIZE(J_z,1)))
  ALLOCATE(P_AVG(SIZE(J_z,1),SIZE(J_z,1)))
  ALLOCATE(U_AUX(SIZE(J_z,1),SIZE(J_z,1)))
  H__ = J_z
  CALL LAPACK_FULLEIGENVALUES(H__,ID%D_BARE,Energy,INFO)
  WRITE(*,*) ENERGY
  DEALLOCATE(H__)
  DEALLOCATE(ENERGY) 
  
  ALLOCATE(MODES_NUM(4))

  MODES_NUM(1) = 1 !(STATIC FIELD)
  MODES_NUM(2) = 1 !(DRIVING BY TWO HARMONICS)
  MODES_NUM(3) = 1 !(DRVING BY A SECOND FREQUENCY)
  MODES_NUM(4) = 1 !(DRVING BY A SECOND FREQUENCY)
  
  TOTAL_FREQUENCIES = SUM(MODES_NUM,1)
  ALLOCATE(FIELDS(TOTAL_FREQUENCIES))
  DO m=1,TOTAL_FREQUENCIES
     ALLOCATE(FIELDS(m)%V(ID%D_BARE,ID%D_BARE))
  END DO
  
  FIELDS(1)%x = 0.0
  FIELDS(1)%y = 0.0
  FIELDS(1)%z = 1.0
  FIELDS(1)%phi_x = 0.0
  FIELDS(1)%phi_y = 0.0
  FIELDS(1)%phi_z = 1.0
  FIELDS(1)%omega = 0.0
  FIELDS(1)%N_Floquet = 0

  FIELDS(2)%x = 0.1625
  FIELDS(2)%y = 0.0
  FIELDS(2)%z = 0.0
  FIELDS(2)%phi_x = 0.0
  FIELDS(2)%phi_y = 0.0
  FIELDS(2)%phi_z = 0.0
  FIELDS(2)%omega = 1.0
  FIELDS(2)%N_Floquet = 4

  FIELDS(3)%x = 0.125*FIELDS(2)%x/2.0
  FIELDS(3)%y = 0.0
  FIELDS(3)%z = 0.125*FIELDS(2)%x/2.0
  FIELDS(3)%phi_x = 0.0
  FIELDS(3)%phi_y = 0.0
  FIELDS(3)%phi_z = 0.0
  FIELDS(3)%omega = FIELDS(2)%x/2.0
  FIELDS(3)%N_Floquet = 3

  FIELDS(4)%x    = 0.0
  FIELDS(4)%y    = 1.0
  FIELDS(4)%z   = 1.0
  FIELDS(4)%phi_x = 0.0
  FIELDS(4)%phi_y = 0.0
  FIELDS(4)%phi_z = 1.0
  FIELDS(4)%omega = 0.1
  FIELDS(4)%N_Floquet = 2


  CALL SETHAMILTONIANCOMPONENTS(ID,size(modes_num,1),total_frequencies,MODES_NUM,FIELDS,INFO)
  
  !--- FIND THE MULTIMODE FLOQUET SPECTRUM 
  CALL MULTIMODEFLOQUETMATRIX(ID,size(modes_num,1),total_frequencies,MODES_NUM,FIELDS,INFO)
  WRITE(*,*)
  WRITE(*,*)
  ALLOCATE(E_FLOQUET(SIZE(H_FLOQUET,1)))
  E_FLOQUET = 0.0  
  CALL LAPACK_FULLEIGENVALUES(H_FLOQUET,SIZE(H_FLOQUET,1),E_FLOQUET,INFO)
  U_F = H_FLOQUET ! FOURIER DECOMPOSITION OF THE STATES DRESSED BY MODE NUMBER 
  DEALLOCATE(H_FLOQUET)

  ! Evaluate avg transition probabilities in the bare basis
  P_AVG = 0.0
  WRITE(*,*) ID%D_BARE
  CALL MULTIMODETRANSITIONAVG(SIZE(U_F,1),TOTAL_FREQUENCIES,FIELDS,U_F,E_FLOQUET,ID%D_BARE,P_AVG,INFO) 
  CALL WRITE_MATRIX(P_AVG)

  ! EVALUATE INSTANTANEOUS MULTIMODE FLOQUET TRANSFORMATION
  ALLOCATE(U_B2D(ID%D_BARE,SIZE(U_F,1)))
  T1 = 0.0
  write(*,*) size(modes_num,1)
  CALL MULTIMODEFLOQUETTRANSFORMATION(SIZE(U_F,1),SIZE(MODES_NUM,1),U_F,E_FLOQUET,ID%D_BARE,FIELDS,T1,U_B2D,INFO) 

  !EVALUATE TIME-EVOLUTION OPERATOR IN THE BARE BASIS
  T1 = 0.0
  T2 = 0.125
  CALL MULTIMODETIMEEVOLUTINOPERATOR(SIZE(U_F,1),SIZE(MODES_NUM,1),U_F,E_FLOQUET,ID%D_BARE,FIELDS,T1,T2,U_AUX,INFO) 
  CALL WRITE_MATRIX(ABS(U_AUX))


  !------TRANSFORM THE TIME-EVOLUTION OPERATOR TO THE DRESSED BASIS
  ! ---- BUILD THE TIME-DEPENDENT TRANSFORMATIONO BETWEEN THE BARE AND THE RF DRESSED BASIS: U_F1

  info =0  
  ALLOCATE(U_F1(ID%D_BARE,SIZE(U_F,1)))
  ALLOCATE(U_F2(ID%D_BARE,SIZE(U_F,1)))
  ALLOCATE(U_F1_red(ID%D_BARE,ID%D_BARE))
  ALLOCATE(U_F2_red(ID%D_BARE,ID%D_BARE))
  
  U_F1=0.0
  U_F2=0.0
  CALL MULTIMODEFLOQUETTRANSFORMATION(SIZE(U_F,1),SIZE(MODES_NUM,1),U_F,E_FLOQUET,ID%D_BARE,FIELDS,T1,U_F1,INFO) 
  CALL MULTIMODEFLOQUETTRANSFORMATION(SIZE(U_F,1),SIZE(MODES_NUM,1),U_F,E_FLOQUET,ID%D_BARE,FIELDS,T2,U_F2,INFO) 
  ! ---- SINGLE OUT ONE DRESSED SUBSPACE
  U_F1_red = 0.0
  INDEX0 = ID%D_BARE*FIELDS(2)%N_FLOQUET
  U_F1_red = U_F1(1:ID%D_BARE,INDEX0+1:INDEX0+ID%D_BARE)
  
  U_F2_red = 0.0
  INDEX0 = ID%D_BARE*FIELDS(2)%N_FLOQUET
  U_F2_red = U_F2(1:ID%D_BARE,INDEX0+1:INDEX0+ID%D_BARE)
  
  ! ---- CALCULATE THE TIME-EVOLUTION OPERATOR IN THE DRESSED BASIS USING THE PREVIOUSLY CALCULATED IN THE BARE BASIS
  U_AUX = MATMUL(TRANSPOSE(CONJG(U_F2_red)),MATMUL(U_AUX,U_F1_red)) ! HERE, P_AUX SHOULD BE OF DIMENSION D_BARE X D_BARE

  CALL WRITE_MATRIX(ABS(U_AUX)**2)
  
END PROGRAM MULTIMODEFLOQUET

