
PROGRAM MANYBODYHUBBARD

  USE ATOMIC_PROPERTIES
  USE TYPES
  USE SUBINTERFACE
  USE SUBINTERFACE_LAPACK
  USE FLOQUETINITINTERFACE
  USE ARRAYS 


  IMPLICIT NONE
  TYPE(MODE),       DIMENSION(:),   ALLOCATABLE :: FIELDS
  TYPE(ATOM)                                       ID
  INTEGER,          DIMENSION(:),   ALLOCATABLE :: MODES_NUM
  INTEGER                                          TOTAL_FREQUENCIES,D_BARE
  INTEGER                                          INFO,m,INDEX0,r
  DOUBLE PRECISION, DIMENSION(:),   ALLOCATABLE :: ENERGY,E_FLOQUET,E_BARE
  COMPLEX*16,       DIMENSION(:,:), ALLOCATABLE :: H_J,H_U,U_F,H_BARE
  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: P_AVG
  INTEGER         , DIMENSION(:,:), ALLOCATABLE :: states_occ
  DOUBLE PRECISION                              :: T1,T2

  INTEGER index,N_BODIES,N_SITES,i_,M_
  DOUBLE PRECISION t,u,t_driv,omega,D_H

  OPEN(UNIT=3,FILE="ManybodyHubbard_Bosons.dat",ACTION="WRITE")
  
  INFO = 0
  N_BODIES = 7
  
  N_SITES  = 3
  
  
  
  D_BARE = D_H(N_SITES,N_BODIES,'B')  ! D_H EVALUATES THE NUMBER OF STATES  
  write(*,*) '# Number of lattice sites:         ', N_SITES
  write(*,*) '# Number of particles:             ', N_BODIES
  write(*,*) '# Number of states Bosonic states  ', D_BARE
  write(*,*)
  write(*,*)

  
  
  CALL FLOQUETINIT(ID,'lattice',0.1d1*D_BARE,INFO)

  ALLOCATE(E_BARE(D_BARE))             ! STORE THE ENERGY SPECTRUM
  ALLOCATE(H_BARE(D_BARE,D_BARE))      ! STORE THE BARE HAMILTONIAN
  ALLOCATE(H_J(D_BARE,D_BARE))         ! STORE THE TUNNENING MATRIX
  ALLOCATE(H_U(D_BARE,D_BARE))         ! STORES THE ONSITE INTERACTION
  ALLOCATE(MODES_NUM(2))               ! NUMBER OF DRIVING MODES
  
  
  ALLOCATE(states_occ(D_BARE,N_SITES)) ! STORES THE STATES USING OCCUPATION NUMBER 

   ! CREATE THE BASIS OF STATES
  CALL Manybody_basis(D_BARE,N_SITES,N_BODIES,'B',states_occ,INFO)
  !call write_matrix_int(states_occ)
  
  
  
!  ! EVALUATE THE TUNNELING TERM OF THE HAMILTONIAN
  
  
  
  
  
  
  
  
  
  CALL Tunneling_B(D_BARE,N_SITES,N_BODIES,STATES_OCC,H_J,INFO)
!  !CALL WRITE_MATRIX(abs(h_j))
!  !! EVALUATE THE ON-SITE INTERACTION
  
  CALL Onsite_twobody_B(D_BARE,N_SITES,N_BODIES,STATES_OCC,H_U,INFO)
!  !CALL WRITE_MATRIX(abs(h_u))
!
  !NOW DEFINE THE DRIVING 
  MODES_NUM(1) = 1 !(STATIC FIELD)
  MODES_NUM(2) = 1 !(DRIVING BY ONE HARMONIC)
!  
  TOTAL_FREQUENCIES = SUM(MODES_NUM,1)
  ALLOCATE(FIELDS(TOTAL_FREQUENCIES))
  DO m=1,TOTAL_FREQUENCIES
     ALLOCATE(FIELDS(m)%V(D_BARE,D_BARE))
     FIELDS(m)%V = 0.0
  END DO
  
  ! HUBBARD MODEL PARAMETERS
  t      = 1.0
  u      = 0.5
  
  !DRIVING PARAMETERS
  t_driv = 0.2
  omega  = 1.0

  ! DEFINE THE TOTAL STATIC HAMILTONIAN USIING THE TUNNELING AND ON-SITE INTERACTIONS
  FIELDS(1)%V         = -t*H_J + u*H_U
  FIELDS(1)%omega     = 0
  FIELDS(1)%N_Floquet = 0
  
  ! DEFINE THE DRIVING TERM OF THE HAMILTONIAN.
  FIELDS(2)%V         = t_driv*H_J
  FIELDS(2)%omega     = omega
  FIELDS(2)%N_Floquet = 2
  
  write(*,*) '# Hubbard parameters (t,u):',t,u
  write(*,*) '# Driving parameters (t_driving,omega,N_Floquet):',t_driv,omega,FIELDS(2)%N_Floquet
  write(*,*) '# Floquet spectrum as a function of the driving frequency (first column))'


  ! EVALUATE THE SPECTRUM OF THE STATIC HAMILTONIAN
  H_BARE = FIELDS(1)%V
  CALL LAPACK_FULLEIGENVALUES(H_BARE,D_BARE,E_BARE,INFO)
  M_=32
  DO m=1,M_ ! SCAN DRIVING FREQUENCY
    FIELDS(2)%omega     = 0.1 + (m-1)*1.0/M_
    CALL MULTIMODEFLOQUETMATRIX(ID,size(modes_num,1),total_frequencies,MODES_NUM,FIELDS,INFO)
!  !CALL WRITE_MATRIX(ABS(H_FLOUET()))
!
    ALLOCATE(E_FLOQUET(SIZE(H_FLOQUET,1)))
    ALLOCATE(U_F(SIZE(H_FLOQUET,1),SIZE(H_FLOQUET,1)))
    E_FLOQUET = 0.0   
!  
    CALL LAPACK_FULLEIGENVALUES(H_FLOQUET,SIZE(H_FLOQUET,1),E_FLOQUET,INFO)
    U_F = H_FLOQUET ! FOURIER DECOMPOSITION OF THE STATES DRESSED BY MODE NUMBER 
    WRITE(3,*) FIELDS(2)%omega,E_FLOQUET
    DEALLOCATE(H_FLOQUET)
    DEALLOCATE(E_FLOQUET)
    DEALLOCATE(U_F)
    
  END DO
   
END PROGRAM MANYBODYHUBBARD

