SUBROUTINE MKLSPARSE_FULLEIGENVALUES_C(D,E_L,E_R,E_FLOQUET,U_F,INFO)

!CALCULATES THE ENERGY SPECTRUM OF THE MATRIX REPRESENTED BY VALUES, ROW_INDEX AND COLUMN
! D (IN), MATRIX DIMENSION == NUMBER OF EIGENVALUES
! DV (IN), NUMBER OF VALUES != 0
! VALUES (IN) ARRAY OF VALUES
! ROW_INDEX (IN), ARRAY OF INDICES
! COLUMN (IN),    ARRAY OF COLUMN NUMBERS
! E_L (IN),       LEFT BOUNDARY OF THE SEARCH INTERVAL
! E_R (IN),       RIGHT BOUNDARY OF THE SEARCH INTERVAL
! E_FLOQUET (OUT), ARRAY OF EIGENVALUES
! INFO     (INOUT)  ERROR FLAG

  USE MODES_4F
  USE FEAST
  IMPLICIT NONE
  INTEGER,                          INTENT(IN)    :: D
  DOUBLE PRECISION,                 INTENT(IN)    :: E_L,E_R
  DOUBLE PRECISION, DIMENSION(D),   INTENT(OUT)   :: E_FLOQUET
  COMPLEX*16,       DIMENSION(D,D), INTENT(OUT)   :: U_F
  INTEGER,                          INTENT(INOUT) :: INFO

  INTEGER DV
  
  DV = SIZE(VALUES__,1)
  CALL MKLSPARSE_FULLEIGENVALUES(D,DV,VALUES__,ROW_INDEX__,COLUMN__,E_L,E_R,E_FLOQUET,U_F,INFO)
  
  
END SUBROUTINE MKLSPARSE_FULLEIGENVALUES_C

