SUBROUTINE DRESSEDBASIS_SP_C(D,ID,NM,MODES_NUM,FIELDS,U_FD,E_DRESSED,INFO)

!!$THIS SUBROUTINES CALCULATES THE TRANSFORMATION BETWEEN THE BARE BASIS TO THE DRESSED BASIS DEFINDED BY THE FULL SET OF DRIVING FIELDS.
!!$ D                            : DIMENSION OF THE MULTIMODE EXTENDED HILBERT SPACE
!!$ ID (IN)                      : TYPE OF QUATUM SYSTEM
!!$ NM (IN)                      : NUMBER OF MODES == NUMBER OF DRIVING FIELDS
!!$ MODES_NUM                    : VECTOR INDICATING THE NUMBER OF HARMONICS OF EACH DRESSING FIELD
!!$ FIELDS (IN)                  : AMPLITUDE, FREQUENCY AND PHASES OF ALL DRIVING FIELDS
!!$ U_FD (OUT)                   : THIS IS THE TRANSFORMATION WE ARE LOOKING FOR
!!$ E_DRESSED (OUT)              : DRESSED ENERGIES
!!$ INFO (INOUT)                 : INFO = 0 MEANS SUCESS
               

  
  USE TYPES_C
  USE TYPES
  USE MODES_4F
  
  IMPLICIT NONE
  TYPE(MODE_C),     DIMENSION(NM),  INTENT(IN)    :: FIELDS
  TYPE(ATOM_C),                     INTENT(IN)    :: ID
  INTEGER,          DIMENSION(NM),  INTENT(IN)    :: MODES_NUM
  COMPLEX*16,       DIMENSION(D,D), INTENT(OUT)   :: U_FD
  DOUBLE PRECISION, DIMENSION(D),   INTENT(OUT)   :: E_DRESSED
  INTEGER,                          INTENT(IN)    :: NM,D
  INTEGER,                          INTENT(INOUT) :: INFO

  CALL DRESSEDBASIS_SP(D,ATOM_,NM,MODES_NUM,COUPLING,U_FD,E_DRESSED,INFO)

  
END SUBROUTINE DRESSEDBASIS_SP_C


SUBROUTINE DRESSEDBASIS_SUBSET_SP_C(ID,DRESSINGFLOQUETDIMENSION,DRESSINGFIELDS,NM,&
        & DRESSINGFIELDS_INDICES,MODES_NUM,FIELDS,U_FD,E_DRESSED,INFO)

!!$THIS SUBROUTINES CALCULATES THE TRANSFORMATION BETWEEN THE BARE BASIS TO THE DRESSED BASIS DEFINDED BY A SUBSET OF THE DRIVING FIELDS.
!!$
!!$ ID (IN)                      : TYPE OF QUATUM SYSTEM
!!$ DRESSINGFLOQUETDIMENSION(IN) : DIMENSION OF THE DRESSED FLOQUET HILBERT SPACE
!!$ DRESSINGFIELDS (IN)          : NUMBER OF DRESSING FIELDS
!!$ NM (IN)                      : NUMBER OF MODES == NUMBER OF DRIVING FIELDS
!!$ DRESSINGFIELDS_INDICES       : OUT OF ALL THE DRIVING FIELDS, THIS VECTOR INDICATES THE INDEX OF THE DRESSING FIELD
!!$ MODES_NUM                    : VECTOR INDICATING THE NUMBER OF HARMONICS OF EACH DRESSING FIELD
!!$ FIELDS (IN)                  : AMPLITUDE, FREQUENCY AND PHASES OF ALL DRIVING FIELDS
!!$ U_FD (OUT)                   : THIS IS THE TRANSFORMATION WE ARE LOOKING FOR
!!$ E_DRESSED (OUT)              : DRESSED ENERGIES
!!$ INFO (INOUT)                 : INFO = 0 MEANS SUCESS
               

  USE TYPES_C
  USE TYPES
  USE MODES_4F

  IMPLICIT NONE
  INTEGER,                                               INTENT(IN)    :: NM
  INTEGER,                                               INTENT(IN)    :: DRESSINGFLOQUETDIMENSION,DRESSINGFIELDS
  TYPE(MODE_C), DIMENSION(NM),                           INTENT(IN)    :: FIELDS
  TYPE(ATOM_C),                                          INTENT(IN)    :: ID
  INTEGER,    DIMENSION(DRESSINGFIELDS),                 INTENT(IN)    :: DRESSINGFIELDS_INDICES
  INTEGER,    DIMENSION(NM),                             INTENT(IN)    :: MODES_NUM
  COMPLEX*16, DIMENSION(DRESSINGFLOQUETDIMENSION,DRESSINGFLOQUETDIMENSION),       INTENT(OUT)   :: U_FD
  DOUBLE PRECISION, DIMENSION(DRESSINGFLOQUETDIMENSION), INTENT(OUT)   :: E_DRESSED
  INTEGER,                                               INTENT(INOUT) :: INFO

  INTEGER,    DIMENSION(DRESSINGFIELDS):: DRESSINGFIELDS_INDICES_
  DRESSINGFIELDS_INDICES_ = DRESSINGFIELDS_INDICES + 1

  CALL DRESSEDBASIS_SUBSET_SP(ATOM_,DRESSINGFLOQUETDIMENSION,DRESSINGFIELDS,NM,&
        & DRESSINGFIELDS_INDICES_,MODES_NUM,COUPLING,U_FD,E_DRESSED,INFO)
  
  
END SUBROUTINE DRESSEDBASIS_SUBSET_SP_C
