SUBROUTINE TIMEEVOLUTIONOPERATOR_C(ATOM__C,D_BARE,NM,NF,MODES_NUM,COUPLING_C,T1,T2,U,INFO) 
!SUBROUTINE TIMEEVOLUTIONOPERATOR_C(ATOM__C,D_BARE,NM,NF,MODES_NUM,COUPLING_C,T1,T2,INFO) 
  ! TIME EVOLUTION OPERATOR OF A MULTIMODE DRESSED SYSTEM. THE EVOLUTION OPERATOR IS WRITEN IN THE BASIS USED TO EXPRESS THE 
  ! MULTIMODE FLOQUET HAMILTONIAN
  ! U : MATRIX OF AMPLITUED OF PROBABILITIES FOR TRANSITIONS BETWEEN T1 TO T2
!!$  NM             (IN)   : NUMBER OF MODES       
!!$  NF             (IN)   : TOTAL NUMBER OF FREQUENCIES     
!!$  MODES_NUM      (IN)   : VECTOR (NM) INDICATING THE NUMBER OF HARMONICS OF EACH MODE
!!$  D_BARE         (IN)   : DIMENSION OF THE BARE HILBERT SPACE
!!$  FIELD          (IN)   : STRUCTURE DESCRIBING THE COUPLINGS
!!$  T1             (IN)   : INITIAL TIME
!!$  T2             (IN)   : FINAL TIME
!!$  U              (OUT)  : TRANFORMATION BETWEEN THE EXTENDED BARE BASIS AND THE FLOQUET STATES, DIMENSION (D_BARE,D)
!!$  INFO           (INOUT): (POSSIBLE) ERROR FLAG
    
    USE TYPES_C
    USE TYPES
    USE MODES_4F

   ! USE ATOMIC_PROPERTIES
   ! USE TYPES
   ! USE SUBINTERFACE
   ! USE SUBINTERFACE_LAPACK
   ! USE FLOQUETINITINTERFACE
   ! USE ARRAYS 

    
    IMPLICIT NONE
    TYPE(ATOM_C) ,                              INTENT(IN)    :: ATOM__C
    INTEGER,                                    INTENT(IN)    :: D_BARE
    INTEGER,                                    INTENT(IN)    :: NM,NF
    INTEGER,          DIMENSION(NM),            INTENT(IN)    :: MODES_NUM
    TYPE(MODE_C),     DIMENSION(NF),            INTENT(INOUT) :: COUPLING_C  ! FIELDS PROPERTIES: FREQUENCY, AMPLITUDES AND PHASES
    DOUBLE PRECISION,                           INTENT(IN)    :: T1
    DOUBLE PRECISION,                           INTENT(IN)    :: T2
    COMPLEX*16,       DIMENSION(D_BARE,D_BARE), INTENT(INOUT)   :: U
    INTEGER,                                    INTENT(INOUT) :: INFO


    !write(*,*) atom__c%id_system,d_bare,atom__c%d_bare,NF,info
    ! IN THIS SUBROUTINE WE USE THE C STRUCTURES ATOM__C AND COUPLING_C
    ! TO DEFINE AND INITIALISE THE GLOBAL FORTRAN TYPES ATOM_ AND COUPLING
    ! THESE TWO TYPES ARE THEN PASSED ON TO THE ALL OTHER ROUTINES
    CALL COUPLINGINIT_C(ATOM__C%D_BARE,NF,ATOM__C,COUPLING_C,INFO) 
    CALL TIMEEVOLUTIONOPERATOR(ATOM_,D_BARE,NM,NF,MODES_NUM,COUPLING,T1,T2,U,INFO) 
    
END SUBROUTINE TIMEEVOLUTIONOPERATOR_C

