SUBROUTINE TIMEEVOLUTIONOPERATOR(ID,D_BARE,NM,MODES_NUM,FIELD,T1,T2,U,INFO) 
  ! TIME EVOLUTION OPERATOR OF A MULTIMODE DRESSED SYSTEM. THE EVOLUTION OPERATOR IS WRITEN IN THE BASIS USED TO EXPRESS THE 
  ! MULTIMODE FLOQUET HAMILTONIAN
  ! U : MATRIX OF AMPLITUED OF PROBABILITIES FOR TRANSITIONS BETWEEN T1 TO T2
!!$  NM             (IN)   : NUMBER OF MODES            
!!$  MODES_NUM      (IN)   : VECTOR (NM) INDICATING THE NUMBER OF HARMONICS OF EACH MODE
!!$  D_BARE         (IN)   : DIMENSION OF THE BARE HILBERT SPACE
!!$  FIELD          (IN)   : STRUCTURE DESCRIBING THE COUPLINGS
!!$  T1             (IN)   : INITIAL TIME
!!$  T2             (IN)   : FINAL TIME
!!$  U              (OUT)  : TRANFORMATION BETWEEN THE EXTENDED BARE BASIS AND THE FLOQUET STATES, DIMENSION (D_BARE,D)
!!$  INFO           (INOUT): (POSSIBLE) ERROR FLAG
    
    USE ATOMIC_PROPERTIES
    USE TYPES
    USE SUBINTERFACE
    USE SUBINTERFACE_LAPACK
!    USE FLOQUETINIT_ 
    USE ARRAYS 

    
    IMPLICIT NONE
    TYPE(ATOM) ,                                INTENT(IN)    :: ID
    INTEGER,                                    INTENT(IN)    :: D_BARE
    INTEGER,                                    INTENT(IN)    :: NM
    INTEGER,          DIMENSION(NM),            INTENT(IN)    :: MODES_NUM
    TYPE(MODE),       DIMENSION(NM),            INTENT(IN)    :: FIELD  ! FIELDS PROPERTIES: FREQUENCY, AMPLITUDES AND PHASES
    DOUBLE PRECISION,                           INTENT(IN)    :: T1
    DOUBLE PRECISION,                           INTENT(IN)    :: T2
    COMPLEX*16,       DIMENSION(D_BARE,D_BARE), INTENT(OUT)   :: U
    INTEGER,                                    INTENT(INOUT) :: INFO
    
    INTEGER :: TOTAL_FREQUENCIES
    DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: E_FLOQUET
    COMPLEX*16, DIMENSION(:,:), ALLOCATABLE :: U_F
    
    
    TOTAL_FREQUENCIES = SUM(MODES_NUM,1)

    
    IF(ID%id_system .NE. 6) CALL SETHAMILTONIANCOMPONENTS(ID,size(modes_num,1),total_frequencies,MODES_NUM,FIELD,INFO)
    !if id%id_system == 6, then the system is not a spin and the hamiltonian couplings should be defined by hand.
    
    !---- FIND THE MULTIMODE FLOQUET SPECTRUM 
    CALL MULTIMODEFLOQUETMATRIX(ID,size(modes_num,1),total_frequencies,MODES_NUM,FIELD,INFO)
    !write(*,*) A*field(3)%omega/hbar,h_floquet(1,1)

    
    ALLOCATE(E_FLOQUET(SIZE(H_FLOQUET,1)))
    ALLOCATE(U_F(SIZE(H_FLOQUET,1),SIZE(H_FLOQUET,1)))
    E_FLOQUET = 0.0  
    !CALL WRITE_MATRIX(ABS(H_FLOQUET))
    CALL LAPACK_FULLEIGENVALUES(H_FLOQUET,SIZE(H_FLOQUET,1),E_FLOQUET,INFO)
    U_F = H_FLOQUET ! FOURIER DECOMPOSITION OF THE STATES DRESSED BY MODE NUMBER 
    !CALL WRITE_MATRIX(ABS(H_FLOQUET))
    DEALLOCATE(H_FLOQUET)
    !write(*,*) E_FLOQUET
    !--- EVALUATE TIME-EVOLUTION OPERATOR IN THE BARE BASIS
    CALL MULTIMODETIMEEVOLUTINOPERATOR(SIZE(U_F,1),SIZE(MODES_NUM,1),MODES_NUM,U_F,E_FLOQUET,ID%D_BARE,FIELD,T1,T2,U,INFO) 
!    WRITE(*,*) (FIELD(3)%OMEGA)/(2*pi),T2,abs(U)**2

    DEALLOCATE(E_FLOQUET)
    DEALLOCATE(U_F)
  

    
END SUBROUTINE TIMEEVOLUTIONOPERATOR

