MODULE SPARSE_INTERFACE
  INTERFACE
     SUBROUTINE MULTIMODEFLOQUETMATRIX_SP(ATOM_,NM,NF,MODES_NUM,FIELDS,VALUES_,ROW_INDEX_,COLUMN_,INFO)
       USE TYPES
       IMPLICIT NONE
       INTEGER                  ,INTENT(IN)    :: NM,NF
       TYPE(MODE), DIMENSION(NF),INTENT(INOUT) :: FIELDs
       TYPE(ATOM),               INTENT(IN)    :: ATOM_
       INTEGER, DIMENSION(NM),   INTENT(IN)    :: MODES_NUM
       INTEGER,                  INTENT(INOUT) :: INFO
       COMPLEX*16, DIMENSION(:), ALLOCATABLE,INTENT(OUT) :: VALUES_
       INTEGER,    DIMENSION(:), ALLOCATABLE,INTENT(OUT) :: COLUMN_
       INTEGER,    DIMENSION(:), ALLOCATABLE,INTENT(OUT) :: ROW_INDEX_
     END SUBROUTINE MULTIMODEFLOQUETMATRIX_SP
  END INTERFACE
END MODULE SPARSE_INTERFACE
