SUBROUTINE TESTUNITARITY(N,U,DELTA,INFO)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: N
  COMPLEX*16, DIMENSION(N,N), INTENT(IN) :: U_F
  INTEGER, INTENT(INOUT) :: INFO
  DOUBLE PRECISION, INTENT(OUT) :: DELTA
  
  
  DOUBLE PRECISION, DIMENSION(N,N) :: P
  INTEGER i_

  P = MATMUL(TRANSPOSE(CONJG(U_F)),U_F))

  DELTA = 0.0

  DO i_=1,N

     DELTA = DELTA  +  ABS(P(i_,i_) - 1.0)

  END DO


  

END SUBROUTINE TESTUNITARITY
